version: '2'
services:

  postgres:
    image: postgres:11-alpine
    container_name: "postgres-database"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "mypassword"
    volumes:
      - /home/evyatar/work/quarkus/news-quarkus/src/main/resources/init:/docker-entrypoint-initdb.d/

  my-quarkus-app:
    container_name: quarkus-app
    image: quarkus-sample-jvm:latest
    entrypoint: /deployments/run-java.sh
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      MY_NAME: "Evyatar"
    depends_on:
      - postgres

  monitoring:
    image: "prom/prometheus"
    network_mode: 'host' # On Linux, this is required to let Prometheus access the other containers.
    container_name: "super-visor"
    ports:
      - 9090:9090
    volumes:
      - ./src/main/resources/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_ALERTING_ERROR_OR_TIMEOUT=keep_state
