version: '2'
services:

  postgres:
    image: postgres:11-alpine
    container_name: "postgres-database"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "mypassword"
    volumes:
      - /home/evyatar/work/quarkus/news-quarkus/src/main/resources/init:/docker-entrypoint-initdb.d/

  my-quarkus-app:
    container_name: quarkus-app
    image: evyatark/quarkus-sample-app:1.0.0-SNAPSHOT
    entrypoint: /deployments/run-java.sh
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      MY_NAME: "Guy"
    restart: always
    depends_on:
      - postgres

  grafana:
    image: grafana/grafana
    network_mode: 'host' # On Linux, this is required to let Prometheus access the other containers.
    container_name: "grafana1"
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./src/main/resources/monitoring:/var/lib/grafana

  monitoring:
    image: "prom/prometheus"
    network_mode: 'host' # On Linux, this is required to let Prometheus access the other containers.
    container_name: "prometheus"
    ports:
      - 9090:9090
    volumes:
      - ./src/main/resources/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
