global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

# tag::adocPrometheus[]
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:5432']
  - job_name: 'my-quarkus-app'
    static_configs:
      - targets: ['localhost:8080']
# end::adocPrometheus[]
